# Generated by Django 2.1.10 on 2019-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Extension', '0002_auto_20191111_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={'ordering': ('-create_time',), 'permissions': (('sepecial', 'Can publish article'),), 'verbose_name_plural': '扩展用户信息'},
        ),
        migrations.AddField(
            model_name='userextension',
            name='aboutme',
            field=models.CharField(blank=True, max_length=200, verbose_name='自我介绍'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='居住住址'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='学校'),
        ),
    ]
