# Generated by Django 2.2.3 on 2019-11-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_auto_20191122_1114'),
        ('User_Extension', '0003_auto_20191121_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserPosition', to='Department.Position', verbose_name='职位'),
            preserve_default=False,
        ),
    ]
