# Generated by Django 2.2.3 on 2019-11-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_auto_20191122_1114'),
        ('User_Extension', '0004_userextension_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='position',
        ),
        migrations.AddField(
            model_name='userextension',
            name='position',
            field=models.ManyToManyField(related_name='UserPosition', to='Department.Position', verbose_name='职位'),
        ),
    ]
