# Generated by Django 2.1.10 on 2019-11-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisharticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_article', to='User_Extension.UserExtension', verbose_name='作者'),
        ),
    ]
