# Generated by Django 2.2.3 on 2019-11-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_auto_20191122_1114'),
        ('User_Extension', '0005_auto_20191122_1129'),
        ('Publish', '0002_auto_20191112_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200, verbose_name='文章分类')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='User_Extension.UserExtension', verbose_name='作者')),
                ('contains_department', models.ManyToManyField(related_name='contains_department', to='Department.Department', verbose_name='查看白名单')),
                ('excude_department', models.ManyToManyField(related_name='excude_department', to='Department.Department', verbose_name='查看黑名单')),
                ('publish_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_department', to='Department.Department', verbose_name='发布部门')),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'db_table': 'article_column',
                'ordering': ('-create_time', '-change_time'),
            },
        ),
    ]
