# Generated by Django 2.2.3 on 2019-11-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_auto_20191122_1114'),
        ('Publish', '0003_articlecolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecolumn',
            name='contains_department',
        ),
        migrations.RemoveField(
            model_name='articlecolumn',
            name='excude_department',
        ),
        migrations.RemoveField(
            model_name='articlecolumn',
            name='publish_department',
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='contains_department',
            field=models.ManyToManyField(related_name='contains_department', to='Department.Department', verbose_name='查看白名单'),
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='excude_department',
            field=models.ManyToManyField(related_name='excude_department', to='Department.Department', verbose_name='查看黑名单'),
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='publish_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publish_department', to='Department.Department', verbose_name='发布部门'),
            preserve_default=False,
        ),
    ]
