# Generated by Django 2.1.10 on 2019-11-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0004_auto_20191122_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecolumn',
            name='notes',
            field=models.TextField(default='备注信息', verbose_name='备注'),
            preserve_default=False,
        ),
    ]
