# Generated by Django 2.1.10 on 2019-11-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0005_articlecolumn_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisharticle',
            options={'ordering': ('-create_time', '-change_time'), 'verbose_name_plural': '通知'},
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='Publish.ArticleColumn', verbose_name='文章分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='publish_department_position',
            field=models.CharField(default=1, max_length=500, verbose_name='发布人职位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisharticle',
            name='slug',
            field=models.SlugField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='publisharticle',
            name='contains_department',
            field=models.ManyToManyField(blank=True, related_name='contains_department', to='Department.Department', verbose_name='查看白名单'),
        ),
        migrations.AlterField(
            model_name='publisharticle',
            name='excude_department',
            field=models.ManyToManyField(blank=True, related_name='excude_department', to='Department.Department', verbose_name='查看黑名单'),
        ),
        migrations.AlterField(
            model_name='publisharticle',
            name='publish_department',
            field=models.CharField(max_length=500, verbose_name='发布部门'),
        ),
        migrations.AlterIndexTogether(
            name='publisharticle',
            index_together={('id', 'slug', 'title')},
        ),
    ]
