# Generated by Django 2.1.10 on 2019-11-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publish', '0006_auto_20191127_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisharticle',
            name='contains_department',
        ),
        migrations.RemoveField(
            model_name='publisharticle',
            name='excude_department',
        ),
    ]
