# Generated by Django 2.1.10 on 2019-11-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='等级')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='供应商编码')),
                ('supplierName', models.CharField(max_length=50, unique=True, verbose_name='供应商单位名称')),
                ('bankName', models.CharField(max_length=50, verbose_name='开户行')),
                ('accountNumber', models.CharField(max_length=50, unique=True, verbose_name='账号')),
                ('bankNunber', models.CharField(max_length=50, verbose_name='行号')),
                ('dutyParagraph', models.CharField(blank=True, max_length=50, unique=True, verbose_name='税号')),
                ('Note', models.TextField(blank=True, verbose_name='备注')),
                ('state', models.CharField(max_length=20, verbose_name='状态')),
                ('abbreviation', models.CharField(max_length=50, unique=True, verbose_name='简称')),
                ('industryStatus', models.CharField(max_length=20, verbose_name='行业地位')),
                ('entrustName', models.CharField(max_length=10, verbose_name='委托代理联系人姓名')),
                ('entrustTelephone', models.CharField(max_length=11, verbose_name='手机')),
                ('entrustAddress', models.TextField(verbose_name='办公地址')),
                ('entrustZipCode', models.CharField(blank=True, max_length=10, verbose_name='邮编')),
                ('entrustPhone', models.CharField(blank=True, max_length=13, verbose_name='电话')),
                ('entrustFax', models.CharField(blank=True, max_length=13, verbose_name='传真')),
                ('entrustEmail', models.EmailField(max_length=255, verbose_name='通信邮箱')),
                ('registeredAddress', models.TextField(verbose_name='注册地址')),
                ('legalName', models.CharField(max_length=5, verbose_name='法人姓名')),
                ('legalTelephone', models.CharField(blank=True, max_length=11, verbose_name='法人手机')),
                ('legalPhone', models.CharField(blank=True, max_length=13, verbose_name='法人固定电话')),
                ('contact1Name', models.CharField(blank=True, max_length=5, verbose_name='联系人1姓名')),
                ('contact1Post', models.CharField(blank=True, max_length=10, verbose_name='联系人1职务')),
                ('contact1Telephone', models.CharField(blank=True, max_length=11, verbose_name='联系人1手机')),
                ('contact1Phone', models.CharField(blank=True, max_length=13, verbose_name='联系人1固定电话')),
                ('contact1Email', models.EmailField(blank=True, max_length=255, verbose_name='联系人1邮箱')),
                ('contact2Name', models.CharField(blank=True, max_length=5, verbose_name='联系人2姓名')),
                ('contact2Post', models.CharField(blank=True, max_length=10, verbose_name='联系人2职务')),
                ('contact2Telephone', models.CharField(blank=True, max_length=11, verbose_name='联系人2手机')),
                ('contact2Phone', models.CharField(blank=True, max_length=13, verbose_name='联系人2固定电话')),
                ('contact2Email', models.EmailField(blank=True, max_length=255, verbose_name='联系人2邮箱')),
                ('contact3Name', models.CharField(blank=True, max_length=5, verbose_name='联系人3姓名')),
                ('contact3Post', models.CharField(blank=True, max_length=10, verbose_name='联系人3职务')),
                ('contact3Telephone', models.CharField(blank=True, max_length=11, verbose_name='联系人3手机')),
                ('contact3Phone', models.CharField(blank=True, max_length=13, verbose_name='联系人3固定电话')),
                ('contact3Email', models.EmailField(blank=True, max_length=255, verbose_name='联系人3邮箱')),
                ('goodsTypeName', models.CharField(blank=True, max_length=100, verbose_name='物料名称')),
                ('riskStatement', models.TextField(blank=True, verbose_name='风险说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('Planner', models.ManyToManyField(related_name='supplierUser', to=settings.AUTH_USER_MODEL, verbose_name='计划员')),
                ('createName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierCreateName', to=settings.AUTH_USER_MODEL, verbose_name='创建记录员工')),
                ('goodsType', models.ManyToManyField(related_name='supplierGoodsType', to='Classify.GoodsType', verbose_name='产品类型')),
                ('lastEditName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierLastEditName', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑员工')),
                ('riskLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierriskLevel', to='Classify.RiskLevel', verbose_name='风险等级')),
            ],
            options={
                'verbose_name_plural': '供应商信息',
                'db_table': 'supplier',
            },
        ),
    ]
