# Generated by Django 2.2.3 on 2019-11-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierGrade', to='Classify.Grade', verbose_name='供应商等级'),
        ),
    ]
