# Generated by Django 2.2.3 on 2019-11-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_auto_20191106_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierCooperationState', to='Classify.CooperationState', verbose_name='合作状态'),
        ),
    ]
