# Generated by Django 2.2.3 on 2019-11-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_auto_20191106_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='industryStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppelierIndustryStatus', to='Classify.IndustryStatus', verbose_name='行业地位'),
        ),
    ]
