# Generated by Django 2.1.10 on 2019-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_auto_20191106_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('-create_time',), 'verbose_name_plural': '供应商信息'},
        ),
    ]
