# Generated by Django 2.1.10 on 2019-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractEdition', models.CharField(max_length=10, unique=True, verbose_name='合同版本')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '合同版本',
                'db_table': 'contractedition',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsType', models.CharField(max_length=10, unique=True, verbose_name='产品类型')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '产品类型',
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='Invoice_partment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_partment', models.CharField(max_length=10, unique=True, verbose_name='结算单位')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '结算单位',
                'db_table': 'invoice_partment',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskLevel', models.CharField(max_length=10, unique=True, verbose_name='风险等级')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '风险等级',
                'db_table': 'riskLevel',
            },
        ),
        migrations.CreateModel(
            name='SpecialMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialMark', models.CharField(max_length=10, unique=True, verbose_name='特殊标记')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '特殊标记',
                'db_table': 'specialmark',
            },
        ),
    ]
