# Generated by Django 2.2.3 on 2019-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, unique=True, verbose_name='供应商等级')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '供应商等级',
                'db_table': 'grade',
            },
        ),
    ]
