# Generated by Django 2.2.3 on 2019-11-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classify', '0003_cooperationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryStatus', models.CharField(max_length=10, unique=True, verbose_name='行业地位')),
                ('Note', models.CharField(blank=True, max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '行业地位',
                'db_table': 'industrystatus',
            },
        ),
    ]
