# Generated by Django 2.1.10 on 2019-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicdata',
            options={'ordering': ('groupName', 'projectName', 'projectDict', 'projectKey', 'projectValue'), 'verbose_name_plural': '基础数据'},
        ),
    ]
