# Generated by Django 2.1.10 on 2019-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-create_time',), 'verbose_name_plural': '部门'},
        ),
    ]
