# Generated by Django 2.2.3 on 2019-11-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_auto_20191111_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
