# Generated by Django 2.2.3 on 2019-11-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_remove_department_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='position',
        ),
    ]
