# Generated by Django 2.2.3 on 2019-11-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_auto_20191122_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='remarksInformation',
            field=models.TextField(blank=True, verbose_name='备注信息'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=11, verbose_name='职位')),
                ('remarksInformation', models.TextField(blank=True, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Department.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '职位',
                'db_table': 'department_position',
                'ordering': ('-create_time',),
            },
        ),
    ]
