# Generated by Django 2.2.3 on 2019-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0005_auto_20191122_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(max_length=200, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='remarksInformation',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=100, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='position',
            name='remarksInformation',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注信息'),
        ),
    ]
