# Generated by Django 2.2.3 on 2019-11-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_auto_20191122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_position', to='Department.Department', verbose_name='部门'),
        ),
    ]
